services:
  postgres:
    container_name: pacientedb
    image: postgres:latest
    ports:
      - "5545:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pacientedb
    networks:
      - pacientems-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  pacientems-network:

volumes:
  postgres-data:
