version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: sus_connect_exames_db
    environment:
      POSTGRES_DB: sus_connect_exames
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5436:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
